version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pillow
    versions:
    - 8.1.1
    - 8.1.2
    - 8.2.0
  - dependency-name: requests-cache
    versions:
    - 0.6.0
    - 0.6.1
    - 0.6.2
  - dependency-name: gevent
    versions:
    - 21.1.2
  - dependency-name: django
    versions:
    - 3.1.6
    - 3.1.7
  - dependency-name: djangorestframework
    versions:
    - 3.12.3
    - 3.12.4
  - dependency-name: python-dotenv
    versions:
    - 0.16.0
    - 0.17.0
  - dependency-name: gunicorn
    versions:
    - 20.1.0
  - dependency-name: sentry-sdk
    versions:
    - 0.20.0
    - 0.20.2
    - 0.20.3
    - 1.0.0
  - dependency-name: urllib3
    versions:
    - 1.26.3
    - 1.26.4
  - dependency-name: cryptography
    versions:
    - 3.3.2
